### PR TITLE
Review_Code

### PR DESCRIPTION
**Pull request by kaslett**
Please look through these two files:
(1) Figures_in_Main_Paper.R
(2) Figures_Tables_In_Appendix.R

### CODE REVIEW

**Comment by gyaneshg96** [comment]
These comments are after reviewing the Figures_in_Main_Paper.R file.
i) For the various hypotheses in the beginning, a lot of code snippets (such as the one using glmnet) can be written in a function. That will make the code shorter and more readable. As a rule, if a code snipper can be used more than twice, then put it inside a function.
ii) The size of some of the plots are too big. Were they intended to be that size ? 
iii) I saw that 'sd' function is being used a number of times on the same column. Instead of doing this, computer the sd once, and store it in a variable.

**Comment by gyaneshg96** [comment]
Thanks for working on the changes. Some suggestions for the Figures_Tables_in_Appendix.R:
i) There are 'print' statements in each for a loop. Maybe they should be removed from there (as they are not needed).
ii) There are multiple variables like (var1, var2), i.e. list of variables to run and tables_title. Ideally, they can be easily put inside a list and called inside a loop. That will make the code shorter and you can add up more graphs, whenever required.
iii) This one is very minor. There is a variable I think names.use. Based on the naming conventions, it should be names_use. I think it should be easy to change (just find and replace).

**Comment by gyaneshg96** [comment]
Thanks for the changes, I am approving the code.

**Comment by gyaneshg96** [comment]
I think you need to delete the .Rhistory file as well. Maybe delete all the files mentioned in the .gitignore.

**Comment by mabrownnyu** [comment]
Closing PR because code is pushed to the master branch

**Pull request closed without merging**
